Document: vkectl
Title: Debian vkectl Manual
Author: <insert document author here>
Abstract: This manual describes what vkectl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vkectl/vkectl.sgml.gz

Format: postscript
Files: /usr/share/doc/vkectl/vkectl.ps.gz

Format: text
Files: /usr/share/doc/vkectl/vkectl.text.gz

Format: HTML
Index: /usr/share/doc/vkectl/html/index.html
Files: /usr/share/doc/vkectl/html/*.html
