// Code generated by Kitex v0.1.0. DO NOT EDIT.

package resourceservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/addon"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/baremachine"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/clb"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/cluster"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/event"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/helper"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/instance"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/network"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/overview"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/publicverify"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/quota"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/rbac"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/storage"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/trade"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/vci"
	"github.com/volcengine/vkectl/pkg/model/resource/kitex_gen/vpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetClusterOverview(ctx context.Context, req *overview.GetClusterOverviewRequest, callOptions ...callopt.Option) (r *overview.GetClusterOverviewResponse, err error)
	GetKubeConfig(ctx context.Context, req *cluster.GetKubeConfigRequest, callOptions ...callopt.Option) (r *cluster.GetKubeConfigResponse, err error)
	GetKubeconfig(ctx context.Context, req *cluster.GetKubeconfigRequest, callOptions ...callopt.Option) (r *cluster.GetKubeconfigResponse, err error)
	RevokeKubeconfig(ctx context.Context, req *cluster.RevokeKubeconfigRequest, callOptions ...callopt.Option) (r *cluster.RevokeKubeconfigResponse, err error)
	ListKubeconfigUsers(ctx context.Context, req *cluster.ListKubeconfigUsersRequest, callOptions ...callopt.Option) (r *cluster.ListKubeconfigUsersResponse, err error)
	CreateCluster(ctx context.Context, req *cluster.CreateClusterRequest, callOptions ...callopt.Option) (r *cluster.CreateClusterResponse, err error)
	RegisterCluster(ctx context.Context, req *cluster.RegisterClusterRequest, callOptions ...callopt.Option) (r *cluster.RegisterClusterResponse, err error)
	UpdateCluster(ctx context.Context, req *cluster.UpdateClusterRequest, callOptions ...callopt.Option) (r *cluster.UpdateClusterResponse, err error)
	UpgradeCluster(ctx context.Context, req *cluster.UpgradeClusterRequest, callOptions ...callopt.Option) (r *cluster.UpgradeClusterResponse, err error)
	DeleteCluster(ctx context.Context, req *cluster.DeleteClusterRequest, callOptions ...callopt.Option) (r *cluster.DeleteClusterResponse, err error)
	GetCluster(ctx context.Context, req *cluster.GetClusterRequest, callOptions ...callopt.Option) (r *cluster.GetClusterResponse, err error)
	ListClusters(ctx context.Context, req *cluster.ListClustersRequest, callOptions ...callopt.Option) (r *cluster.ListClustersResponse, err error)
	GetClusterDeployProgress(ctx context.Context, req *cluster.GetClusterDeployProgressRequest, callOptions ...callopt.Option) (r *cluster.GetClusterDeployProgressResponse, err error)
	ListSupportedKubernetesVersions(ctx context.Context, req *cluster.ListSupportedKubernetesVersionsRequest, callOptions ...callopt.Option) (r *cluster.ListSupportedKubernetesVersionsResponse, err error)
	ListClusterNetworkCidrs(ctx context.Context, req *cluster.ListClusterNetworkCidrsRequest, callOptions ...callopt.Option) (r *cluster.ListClusterNetworkCidrsResponse, err error)
	ListSupportedGpuModels(ctx context.Context, req *cluster.ListSupportedGpuModelsRequest, callOptions ...callopt.Option) (r *cluster.ListSupportedGpuModelsResponse, err error)
	ListNodes(ctx context.Context, req *cluster.ListNodesRequest, callOptions ...callopt.Option) (r *cluster.ListNodesResponse, err error)
	AddNodes(ctx context.Context, req *cluster.AddNodesRequest, callOptions ...callopt.Option) (r *cluster.AddNodesResponse, err error)
	GetNode(ctx context.Context, req *cluster.GetNodeRequest, callOptions ...callopt.Option) (r *cluster.GetNodeResponse, err error)
	DeleteNodes(ctx context.Context, req *cluster.DeleteNodesRequest, callOptions ...callopt.Option) (r *cluster.DeleteNodesResponse, err error)
	ListNodeLabels(ctx context.Context, req *cluster.ListNodeLabelsRequest, callOptions ...callopt.Option) (r *cluster.ListNodeLabelsResponse, err error)
	UpdateNode(ctx context.Context, req *cluster.UpdateNodeRequest, callOptions ...callopt.Option) (r *cluster.UpdateNodeResponse, err error)
	GetClusterAutoScalingRule(ctx context.Context, req *cluster.GetClusterAutoScalingRuleRequest, callOptions ...callopt.Option) (r *cluster.GetClusterAutoScalingRuleResponse, err error)
	UpdateClusterAutoScalingRule(ctx context.Context, req *cluster.UpdateClusterAutoScalingRuleRequest, callOptions ...callopt.Option) (r *cluster.UpdateClusterAutoScalingRuleResponse, err error)
	ScaleUpNodePool(ctx context.Context, req *cluster.ScaleUpNodePoolRequest, callOptions ...callopt.Option) (r *cluster.ScaleUpNodePoolResponse, err error)
	ScaleDownNodePool(ctx context.Context, req *cluster.ScaleDownNodePoolRequest, callOptions ...callopt.Option) (r *cluster.ScaleDownNodePoolResponse, err error)
	ListNodePools(ctx context.Context, req *cluster.ListNodePoolsRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolsResponse, err error)
	CreateNodePool(ctx context.Context, req *cluster.CreateNodePoolRequest, callOptions ...callopt.Option) (r *cluster.CreateNodePoolResponse, err error)
	GetNodePool(ctx context.Context, req *cluster.GetNodePoolRequest, callOptions ...callopt.Option) (r *cluster.GetNodePoolResponse, err error)
	UpdateNodePool(ctx context.Context, req *cluster.UpdateNodePoolRequest, callOptions ...callopt.Option) (r *cluster.UpdateNodePoolResponse, err error)
	DeleteNodePool(ctx context.Context, req *cluster.DeleteNodePoolRequest, callOptions ...callopt.Option) (r *cluster.DeleteNodePoolResponse, err error)
	ListNodePoolScalingRecords(ctx context.Context, req *cluster.ListNodePoolScalingRecordsRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolScalingRecordsResponse, err error)
	ListNodePoolNodes(ctx context.Context, req *cluster.ListNodePoolNodesRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolNodesResponse, err error)
	ListNamespace(ctx context.Context, req *cluster.ListNamespaceRequest, callOptions ...callopt.Option) (r *cluster.ListNamespaceResponse, err error)
	CreateNamespace(ctx context.Context, req *cluster.CreateNamespaceRequest, callOptions ...callopt.Option) (r *cluster.CreateNamespaceResponse, err error)
	GetNamespace(ctx context.Context, req *cluster.GetNamespaceRequest, callOptions ...callopt.Option) (r *cluster.GetNamespaceResponse, err error)
	UpdateNamespace(ctx context.Context, req *cluster.UpdateNamespaceRequest, callOptions ...callopt.Option) (r *cluster.UpdateNamespaceResponse, err error)
	UpdateNamespaceResource(ctx context.Context, req *cluster.UpdateNamespaceResourceRequest, callOptions ...callopt.Option) (r *cluster.UpdateNamespaceResourceResponse, err error)
	GetNamespaceResource(ctx context.Context, req *cluster.GetNamespaceResourceRequest, callOptions ...callopt.Option) (r *cluster.GetNamespaceResourceResponse, err error)
	DeleteNamespace(ctx context.Context, req *cluster.DeleteNamespaceRequest, callOptions ...callopt.Option) (r *cluster.DeleteNamespaceResponse, err error)
	ListResourceQuota(ctx context.Context, req *cluster.ListResourceQuotaRequest, callOptions ...callopt.Option) (r *cluster.ListResourceQuotaResponse, err error)
	ListIngressTypes(ctx context.Context, req *network.ListIngressTypeRequest, callOptions ...callopt.Option) (r *network.ListIngressTypeResponse, err error)
	ListIngress(ctx context.Context, req *network.ListIngressRequest, callOptions ...callopt.Option) (r *network.ListIngressResponse, err error)
	CreateIngress(ctx context.Context, req *network.CreateIngressRequest, callOptions ...callopt.Option) (r *network.CreateIngressResponse, err error)
	GetIngress(ctx context.Context, req *network.GetIngressRequest, callOptions ...callopt.Option) (r *network.GetIngressResponse, err error)
	UpdateIngress(ctx context.Context, req *network.UpdateIngressRequest, callOptions ...callopt.Option) (r *network.UpdateIngressResponse, err error)
	DeleteIngress(ctx context.Context, req *network.DeleteIngressRequest, callOptions ...callopt.Option) (r *network.DeleteIngressResponse, err error)
	GetSecretDomains(ctx context.Context, req *network.GetSecretDomainsRequest, callOptions ...callopt.Option) (r *network.GetSecretDomainsResponse, err error)
	ListStorageClass(ctx context.Context, req *storage.ListStorageClassRequest, callOptions ...callopt.Option) (r *storage.ListStorageClassResponse, err error)
	CreateStorageClass(ctx context.Context, req *storage.CreateStorageClassRequest, callOptions ...callopt.Option) (r *storage.CreateStorageClassResponse, err error)
	GetStorageClass(ctx context.Context, req *storage.GetStorageClassRequest, callOptions ...callopt.Option) (r *storage.GetStorageClassResponse, err error)
	DeleteStorageClass(ctx context.Context, req *storage.DeleteStorageClassRequest, callOptions ...callopt.Option) (r *storage.DeleteStorageClassResponse, err error)
	ListPersistentVolume(ctx context.Context, req *storage.ListPersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.ListPersistentVolumeResponse, err error)
	CreatePersistentVolume(ctx context.Context, req *storage.CreatePersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.CreatePersistentVolumeResponse, err error)
	GetPersistentVolume(ctx context.Context, req *storage.GetPersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.GetPersistentVolumeResponse, err error)
	DeletePersistentVolume(ctx context.Context, req *storage.DeletePersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.DeletePersistentVolumeResponse, err error)
	ListPersistentVolumeClaim(ctx context.Context, req *storage.ListPersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.ListPersistentVolumeClaimResponse, err error)
	CreatePersistentVolumeClaim(ctx context.Context, req *storage.CreatePersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.CreatePersistentVolumeClaimResponse, err error)
	GetPersistentVolumeClaim(ctx context.Context, req *storage.GetPersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.GetPersistentVolumeClaimResponse, err error)
	DeletePersistentVolumeClaim(ctx context.Context, req *storage.DeletePersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.DeletePersistentVolumeClaimResponse, err error)
	ListCephCluster(ctx context.Context, req *storage.ListCephClusterRequest, callOptions ...callopt.Option) (r *storage.ListCephClusterResponse, err error)
	ListEvent(ctx context.Context, req *event.ListEventRequest, callOptions ...callopt.Option) (r *event.ListEventResponse, err error)
	ListUserRbacs(ctx context.Context, req *rbac.ListUserRbacRequest, callOptions ...callopt.Option) (r *rbac.ListUserRbacResponse, err error)
	CreateUserRbac(ctx context.Context, req *rbac.CreateUserRbacRequest, callOptions ...callopt.Option) (r *rbac.CreateUserRbacResponse, err error)
	UpdateUserRbac(ctx context.Context, req *rbac.UpdateUserRbacRequest, callOptions ...callopt.Option) (r *rbac.UpdateUserRbacResponse, err error)
	DeleteUserRbac(ctx context.Context, req *rbac.DeleteUserRbacRequest, callOptions ...callopt.Option) (r *rbac.DeleteUserRbacResponse, err error)
	ListCustomRoles(ctx context.Context, req *rbac.ListCustomRolesRequest, callOptions ...callopt.Option) (r *rbac.ListCustomRolesResponse, err error)
	ListSupportedAddons(ctx context.Context, req *addon.ListSupportedAddonsRequest, callOptions ...callopt.Option) (r *addon.ListSupportedAddonsResponse, err error)
	ListAddons(ctx context.Context, req *addon.ListAddonsRequest, callOptions ...callopt.Option) (r *addon.ListAddonsResponse, err error)
	InstallAddons(ctx context.Context, req *addon.InstallAddonsRequest, callOptions ...callopt.Option) (r *addon.InstallAddonsResponse, err error)
	ReinstallAddon(ctx context.Context, req *addon.ReinstallAddonRequest, callOptions ...callopt.Option) (r *addon.ReinstallAddonResponse, err error)
	UninstallAddons(ctx context.Context, req *addon.UninstallAddonsRequest, callOptions ...callopt.Option) (r *addon.UninstallAddonsResponse, err error)
	UpgradeAddon(ctx context.Context, req *addon.UpgradeAddonRequest, callOptions ...callopt.Option) (r *addon.UpgradeAddonResponse, err error)
	GetAddon(ctx context.Context, req *addon.GetAddonRequest, callOptions ...callopt.Option) (r *addon.GetAddonResponse, err error)
	CheckResourceExist(ctx context.Context, req *helper.CheckResourceExistRequest, callOptions ...callopt.Option) (r *helper.CheckResourceExistResponse, err error)
	ListInstances(ctx context.Context, req *instance.ListInstancesRequest, callOptions ...callopt.Option) (r *instance.ListInstancesResponse, err error)
	ListFlavors(ctx context.Context, req *instance.ListFlavorsRequest, callOptions ...callopt.Option) (r *instance.ListFlavorsResponse, err error)
	GetInstanceConsole(ctx context.Context, req *instance.GetInstanceConsoleRequest, callOptions ...callopt.Option) (r *instance.GetInstanceConsoleResponse, err error)
	ListZones(ctx context.Context, req *instance.ListZonesRequest, callOptions ...callopt.Option) (r *instance.ListZonesResponse, err error)
	ListVolumes(ctx context.Context, req *instance.ListVolumesRequest, callOptions ...callopt.Option) (r *instance.ListVolumesResponse, err error)
	ListKeyPairs(ctx context.Context, req *instance.ListKeyPairsRequest, callOptions ...callopt.Option) (r *instance.ListKeyPairsResponse, err error)
	ListSubnets(ctx context.Context, req *vpc.ListSubnetsRequest, callOptions ...callopt.Option) (r *vpc.ListSubnetsResponse, err error)
	ListElasticIpPools(ctx context.Context, req *vpc.ListElasticIpPoolsRequest, callOptions ...callopt.Option) (r *vpc.ListElasticIpPoolsResponse, err error)
	ListVpcs(ctx context.Context, req *vpc.ListVpcsRequest, callOptions ...callopt.Option) (r *vpc.ListVpcsResponse, err error)
	ListSecurityGroups(ctx context.Context, req *vpc.ListSecurityGroupsRequest, callOptions ...callopt.Option) (r *vpc.ListSecurityGroupsResponse, err error)
	ListClbs(ctx context.Context, req *clb.ListClbsRequest, callOptions ...callopt.Option) (r *clb.ListClbsResponse, err error)
	ListClbListeners(ctx context.Context, req *clb.ListClbListenersRequest, callOptions ...callopt.Option) (r *clb.ListClbListenersResponse, err error)
	ListQuotas(ctx context.Context, req *quota.ListQuotasRequest, callOptions ...callopt.Option) (r *quota.ListQuotasResponse, err error)
	GetQuota(ctx context.Context, req *quota.GetQuotaRequest, callOptions ...callopt.Option) (r *quota.GetQuotaResponse, err error)
	CreateBareMachine(ctx context.Context, req *baremachine.CreateBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.CreateBareMachineResponse, err error)
	UpdateBareMachine(ctx context.Context, req *baremachine.UpdateBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.UpdateBareMachineResponse, err error)
	DeleteBareMachine(ctx context.Context, req *baremachine.DeleteBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.DeleteBareMachineResponse, err error)
	GetBareMachine(ctx context.Context, req *baremachine.GetBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineResponse, err error)
	ListBareMachine(ctx context.Context, req *baremachine.ListBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.ListBareMachineResponse, err error)
	GetBareMachineSshPublicKey(ctx context.Context, req *baremachine.GetBareMachineSshPublicKeyRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineSshPublicKeyResponse, err error)
	ListBareMachineExpectOs(ctx context.Context, req *baremachine.ListBareMachineExpectOsRequest, callOptions ...callopt.Option) (r *baremachine.ListBareMachineExpectOsResponse, err error)
	GetBareMachineImportExcelTemplate(ctx context.Context, req *baremachine.GetBareMachineImportExcelTemplateRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineImportExcelTemplateResponse, err error)
	CheckCidrConflict(ctx context.Context, req *cluster.CheckCidrConflictRequest, callOptions ...callopt.Option) (r *cluster.CheckCidrConflictResponse, err error)
	RecommendCidr(ctx context.Context, req *cluster.RecommendCidrRequest, callOptions ...callopt.Option) (r *cluster.RecommendCidrResponse, err error)
	AddVciSubnets(ctx context.Context, req *cluster.AddVciSubnetsRequest, callOptions ...callopt.Option) (r *cluster.AddVciSubnetsResponse, err error)
	IsInShortTermWhiteList(ctx context.Context, req *trade.IsInShortTermWhiteListRequest, callOptions ...callopt.Option) (r *trade.IsInShortTermWhiteListResponse, err error)
	AllowUserPublicTest(ctx context.Context, req *publicverify.PublicTestAllowedReq, callOptions ...callopt.Option) (r *publicverify.PublicTestAllowedResp, err error)
	ListVciAvailabilityZones(ctx context.Context, req *vci.ListVciAvailabilityZonesRequest, callOptions ...callopt.Option) (r *vci.ListVciAvailabilityZonesResponse, err error)
	ListNodeZones(ctx context.Context, req *cluster.ListNodeZonesRequest, callOptions ...callopt.Option) (r *cluster.ListNodeZonesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kResourceServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kResourceServiceClient struct {
	*kClient
}

func (p *kResourceServiceClient) GetClusterOverview(ctx context.Context, req *overview.GetClusterOverviewRequest, callOptions ...callopt.Option) (r *overview.GetClusterOverviewResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetClusterOverview(ctx, req)
}

func (p *kResourceServiceClient) GetKubeConfig(ctx context.Context, req *cluster.GetKubeConfigRequest, callOptions ...callopt.Option) (r *cluster.GetKubeConfigResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKubeConfig(ctx, req)
}

func (p *kResourceServiceClient) GetKubeconfig(ctx context.Context, req *cluster.GetKubeconfigRequest, callOptions ...callopt.Option) (r *cluster.GetKubeconfigResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKubeconfig(ctx, req)
}

func (p *kResourceServiceClient) RevokeKubeconfig(ctx context.Context, req *cluster.RevokeKubeconfigRequest, callOptions ...callopt.Option) (r *cluster.RevokeKubeconfigResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeKubeconfig(ctx, req)
}

func (p *kResourceServiceClient) ListKubeconfigUsers(ctx context.Context, req *cluster.ListKubeconfigUsersRequest, callOptions ...callopt.Option) (r *cluster.ListKubeconfigUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKubeconfigUsers(ctx, req)
}

func (p *kResourceServiceClient) CreateCluster(ctx context.Context, req *cluster.CreateClusterRequest, callOptions ...callopt.Option) (r *cluster.CreateClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCluster(ctx, req)
}

func (p *kResourceServiceClient) RegisterCluster(ctx context.Context, req *cluster.RegisterClusterRequest, callOptions ...callopt.Option) (r *cluster.RegisterClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterCluster(ctx, req)
}

func (p *kResourceServiceClient) UpdateCluster(ctx context.Context, req *cluster.UpdateClusterRequest, callOptions ...callopt.Option) (r *cluster.UpdateClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCluster(ctx, req)
}

func (p *kResourceServiceClient) UpgradeCluster(ctx context.Context, req *cluster.UpgradeClusterRequest, callOptions ...callopt.Option) (r *cluster.UpgradeClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpgradeCluster(ctx, req)
}

func (p *kResourceServiceClient) DeleteCluster(ctx context.Context, req *cluster.DeleteClusterRequest, callOptions ...callopt.Option) (r *cluster.DeleteClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCluster(ctx, req)
}

func (p *kResourceServiceClient) GetCluster(ctx context.Context, req *cluster.GetClusterRequest, callOptions ...callopt.Option) (r *cluster.GetClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCluster(ctx, req)
}

func (p *kResourceServiceClient) ListClusters(ctx context.Context, req *cluster.ListClustersRequest, callOptions ...callopt.Option) (r *cluster.ListClustersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListClusters(ctx, req)
}

func (p *kResourceServiceClient) GetClusterDeployProgress(ctx context.Context, req *cluster.GetClusterDeployProgressRequest, callOptions ...callopt.Option) (r *cluster.GetClusterDeployProgressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetClusterDeployProgress(ctx, req)
}

func (p *kResourceServiceClient) ListSupportedKubernetesVersions(ctx context.Context, req *cluster.ListSupportedKubernetesVersionsRequest, callOptions ...callopt.Option) (r *cluster.ListSupportedKubernetesVersionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSupportedKubernetesVersions(ctx, req)
}

func (p *kResourceServiceClient) ListClusterNetworkCidrs(ctx context.Context, req *cluster.ListClusterNetworkCidrsRequest, callOptions ...callopt.Option) (r *cluster.ListClusterNetworkCidrsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListClusterNetworkCidrs(ctx, req)
}

func (p *kResourceServiceClient) ListSupportedGpuModels(ctx context.Context, req *cluster.ListSupportedGpuModelsRequest, callOptions ...callopt.Option) (r *cluster.ListSupportedGpuModelsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSupportedGpuModels(ctx, req)
}

func (p *kResourceServiceClient) ListNodes(ctx context.Context, req *cluster.ListNodesRequest, callOptions ...callopt.Option) (r *cluster.ListNodesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodes(ctx, req)
}

func (p *kResourceServiceClient) AddNodes(ctx context.Context, req *cluster.AddNodesRequest, callOptions ...callopt.Option) (r *cluster.AddNodesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddNodes(ctx, req)
}

func (p *kResourceServiceClient) GetNode(ctx context.Context, req *cluster.GetNodeRequest, callOptions ...callopt.Option) (r *cluster.GetNodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNode(ctx, req)
}

func (p *kResourceServiceClient) DeleteNodes(ctx context.Context, req *cluster.DeleteNodesRequest, callOptions ...callopt.Option) (r *cluster.DeleteNodesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNodes(ctx, req)
}

func (p *kResourceServiceClient) ListNodeLabels(ctx context.Context, req *cluster.ListNodeLabelsRequest, callOptions ...callopt.Option) (r *cluster.ListNodeLabelsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodeLabels(ctx, req)
}

func (p *kResourceServiceClient) UpdateNode(ctx context.Context, req *cluster.UpdateNodeRequest, callOptions ...callopt.Option) (r *cluster.UpdateNodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNode(ctx, req)
}

func (p *kResourceServiceClient) GetClusterAutoScalingRule(ctx context.Context, req *cluster.GetClusterAutoScalingRuleRequest, callOptions ...callopt.Option) (r *cluster.GetClusterAutoScalingRuleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetClusterAutoScalingRule(ctx, req)
}

func (p *kResourceServiceClient) UpdateClusterAutoScalingRule(ctx context.Context, req *cluster.UpdateClusterAutoScalingRuleRequest, callOptions ...callopt.Option) (r *cluster.UpdateClusterAutoScalingRuleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateClusterAutoScalingRule(ctx, req)
}

func (p *kResourceServiceClient) ScaleUpNodePool(ctx context.Context, req *cluster.ScaleUpNodePoolRequest, callOptions ...callopt.Option) (r *cluster.ScaleUpNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ScaleUpNodePool(ctx, req)
}

func (p *kResourceServiceClient) ScaleDownNodePool(ctx context.Context, req *cluster.ScaleDownNodePoolRequest, callOptions ...callopt.Option) (r *cluster.ScaleDownNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ScaleDownNodePool(ctx, req)
}

func (p *kResourceServiceClient) ListNodePools(ctx context.Context, req *cluster.ListNodePoolsRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodePools(ctx, req)
}

func (p *kResourceServiceClient) CreateNodePool(ctx context.Context, req *cluster.CreateNodePoolRequest, callOptions ...callopt.Option) (r *cluster.CreateNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNodePool(ctx, req)
}

func (p *kResourceServiceClient) GetNodePool(ctx context.Context, req *cluster.GetNodePoolRequest, callOptions ...callopt.Option) (r *cluster.GetNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNodePool(ctx, req)
}

func (p *kResourceServiceClient) UpdateNodePool(ctx context.Context, req *cluster.UpdateNodePoolRequest, callOptions ...callopt.Option) (r *cluster.UpdateNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNodePool(ctx, req)
}

func (p *kResourceServiceClient) DeleteNodePool(ctx context.Context, req *cluster.DeleteNodePoolRequest, callOptions ...callopt.Option) (r *cluster.DeleteNodePoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNodePool(ctx, req)
}

func (p *kResourceServiceClient) ListNodePoolScalingRecords(ctx context.Context, req *cluster.ListNodePoolScalingRecordsRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolScalingRecordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodePoolScalingRecords(ctx, req)
}

func (p *kResourceServiceClient) ListNodePoolNodes(ctx context.Context, req *cluster.ListNodePoolNodesRequest, callOptions ...callopt.Option) (r *cluster.ListNodePoolNodesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodePoolNodes(ctx, req)
}

func (p *kResourceServiceClient) ListNamespace(ctx context.Context, req *cluster.ListNamespaceRequest, callOptions ...callopt.Option) (r *cluster.ListNamespaceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNamespace(ctx, req)
}

func (p *kResourceServiceClient) CreateNamespace(ctx context.Context, req *cluster.CreateNamespaceRequest, callOptions ...callopt.Option) (r *cluster.CreateNamespaceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNamespace(ctx, req)
}

func (p *kResourceServiceClient) GetNamespace(ctx context.Context, req *cluster.GetNamespaceRequest, callOptions ...callopt.Option) (r *cluster.GetNamespaceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNamespace(ctx, req)
}

func (p *kResourceServiceClient) UpdateNamespace(ctx context.Context, req *cluster.UpdateNamespaceRequest, callOptions ...callopt.Option) (r *cluster.UpdateNamespaceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNamespace(ctx, req)
}

func (p *kResourceServiceClient) UpdateNamespaceResource(ctx context.Context, req *cluster.UpdateNamespaceResourceRequest, callOptions ...callopt.Option) (r *cluster.UpdateNamespaceResourceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNamespaceResource(ctx, req)
}

func (p *kResourceServiceClient) GetNamespaceResource(ctx context.Context, req *cluster.GetNamespaceResourceRequest, callOptions ...callopt.Option) (r *cluster.GetNamespaceResourceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNamespaceResource(ctx, req)
}

func (p *kResourceServiceClient) DeleteNamespace(ctx context.Context, req *cluster.DeleteNamespaceRequest, callOptions ...callopt.Option) (r *cluster.DeleteNamespaceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNamespace(ctx, req)
}

func (p *kResourceServiceClient) ListResourceQuota(ctx context.Context, req *cluster.ListResourceQuotaRequest, callOptions ...callopt.Option) (r *cluster.ListResourceQuotaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListResourceQuota(ctx, req)
}

func (p *kResourceServiceClient) ListIngressTypes(ctx context.Context, req *network.ListIngressTypeRequest, callOptions ...callopt.Option) (r *network.ListIngressTypeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListIngressTypes(ctx, req)
}

func (p *kResourceServiceClient) ListIngress(ctx context.Context, req *network.ListIngressRequest, callOptions ...callopt.Option) (r *network.ListIngressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListIngress(ctx, req)
}

func (p *kResourceServiceClient) CreateIngress(ctx context.Context, req *network.CreateIngressRequest, callOptions ...callopt.Option) (r *network.CreateIngressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateIngress(ctx, req)
}

func (p *kResourceServiceClient) GetIngress(ctx context.Context, req *network.GetIngressRequest, callOptions ...callopt.Option) (r *network.GetIngressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetIngress(ctx, req)
}

func (p *kResourceServiceClient) UpdateIngress(ctx context.Context, req *network.UpdateIngressRequest, callOptions ...callopt.Option) (r *network.UpdateIngressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateIngress(ctx, req)
}

func (p *kResourceServiceClient) DeleteIngress(ctx context.Context, req *network.DeleteIngressRequest, callOptions ...callopt.Option) (r *network.DeleteIngressResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteIngress(ctx, req)
}

func (p *kResourceServiceClient) GetSecretDomains(ctx context.Context, req *network.GetSecretDomainsRequest, callOptions ...callopt.Option) (r *network.GetSecretDomainsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSecretDomains(ctx, req)
}

func (p *kResourceServiceClient) ListStorageClass(ctx context.Context, req *storage.ListStorageClassRequest, callOptions ...callopt.Option) (r *storage.ListStorageClassResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListStorageClass(ctx, req)
}

func (p *kResourceServiceClient) CreateStorageClass(ctx context.Context, req *storage.CreateStorageClassRequest, callOptions ...callopt.Option) (r *storage.CreateStorageClassResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateStorageClass(ctx, req)
}

func (p *kResourceServiceClient) GetStorageClass(ctx context.Context, req *storage.GetStorageClassRequest, callOptions ...callopt.Option) (r *storage.GetStorageClassResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStorageClass(ctx, req)
}

func (p *kResourceServiceClient) DeleteStorageClass(ctx context.Context, req *storage.DeleteStorageClassRequest, callOptions ...callopt.Option) (r *storage.DeleteStorageClassResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteStorageClass(ctx, req)
}

func (p *kResourceServiceClient) ListPersistentVolume(ctx context.Context, req *storage.ListPersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.ListPersistentVolumeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPersistentVolume(ctx, req)
}

func (p *kResourceServiceClient) CreatePersistentVolume(ctx context.Context, req *storage.CreatePersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.CreatePersistentVolumeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePersistentVolume(ctx, req)
}

func (p *kResourceServiceClient) GetPersistentVolume(ctx context.Context, req *storage.GetPersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.GetPersistentVolumeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPersistentVolume(ctx, req)
}

func (p *kResourceServiceClient) DeletePersistentVolume(ctx context.Context, req *storage.DeletePersistentVolumeRequest, callOptions ...callopt.Option) (r *storage.DeletePersistentVolumeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePersistentVolume(ctx, req)
}

func (p *kResourceServiceClient) ListPersistentVolumeClaim(ctx context.Context, req *storage.ListPersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.ListPersistentVolumeClaimResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPersistentVolumeClaim(ctx, req)
}

func (p *kResourceServiceClient) CreatePersistentVolumeClaim(ctx context.Context, req *storage.CreatePersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.CreatePersistentVolumeClaimResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePersistentVolumeClaim(ctx, req)
}

func (p *kResourceServiceClient) GetPersistentVolumeClaim(ctx context.Context, req *storage.GetPersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.GetPersistentVolumeClaimResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPersistentVolumeClaim(ctx, req)
}

func (p *kResourceServiceClient) DeletePersistentVolumeClaim(ctx context.Context, req *storage.DeletePersistentVolumeClaimRequest, callOptions ...callopt.Option) (r *storage.DeletePersistentVolumeClaimResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePersistentVolumeClaim(ctx, req)
}

func (p *kResourceServiceClient) ListCephCluster(ctx context.Context, req *storage.ListCephClusterRequest, callOptions ...callopt.Option) (r *storage.ListCephClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCephCluster(ctx, req)
}

func (p *kResourceServiceClient) ListEvent(ctx context.Context, req *event.ListEventRequest, callOptions ...callopt.Option) (r *event.ListEventResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListEvent(ctx, req)
}

func (p *kResourceServiceClient) ListUserRbacs(ctx context.Context, req *rbac.ListUserRbacRequest, callOptions ...callopt.Option) (r *rbac.ListUserRbacResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserRbacs(ctx, req)
}

func (p *kResourceServiceClient) CreateUserRbac(ctx context.Context, req *rbac.CreateUserRbacRequest, callOptions ...callopt.Option) (r *rbac.CreateUserRbacResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUserRbac(ctx, req)
}

func (p *kResourceServiceClient) UpdateUserRbac(ctx context.Context, req *rbac.UpdateUserRbacRequest, callOptions ...callopt.Option) (r *rbac.UpdateUserRbacResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserRbac(ctx, req)
}

func (p *kResourceServiceClient) DeleteUserRbac(ctx context.Context, req *rbac.DeleteUserRbacRequest, callOptions ...callopt.Option) (r *rbac.DeleteUserRbacResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserRbac(ctx, req)
}

func (p *kResourceServiceClient) ListCustomRoles(ctx context.Context, req *rbac.ListCustomRolesRequest, callOptions ...callopt.Option) (r *rbac.ListCustomRolesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCustomRoles(ctx, req)
}

func (p *kResourceServiceClient) ListSupportedAddons(ctx context.Context, req *addon.ListSupportedAddonsRequest, callOptions ...callopt.Option) (r *addon.ListSupportedAddonsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSupportedAddons(ctx, req)
}

func (p *kResourceServiceClient) ListAddons(ctx context.Context, req *addon.ListAddonsRequest, callOptions ...callopt.Option) (r *addon.ListAddonsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAddons(ctx, req)
}

func (p *kResourceServiceClient) InstallAddons(ctx context.Context, req *addon.InstallAddonsRequest, callOptions ...callopt.Option) (r *addon.InstallAddonsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InstallAddons(ctx, req)
}

func (p *kResourceServiceClient) ReinstallAddon(ctx context.Context, req *addon.ReinstallAddonRequest, callOptions ...callopt.Option) (r *addon.ReinstallAddonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReinstallAddon(ctx, req)
}

func (p *kResourceServiceClient) UninstallAddons(ctx context.Context, req *addon.UninstallAddonsRequest, callOptions ...callopt.Option) (r *addon.UninstallAddonsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UninstallAddons(ctx, req)
}

func (p *kResourceServiceClient) UpgradeAddon(ctx context.Context, req *addon.UpgradeAddonRequest, callOptions ...callopt.Option) (r *addon.UpgradeAddonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpgradeAddon(ctx, req)
}

func (p *kResourceServiceClient) GetAddon(ctx context.Context, req *addon.GetAddonRequest, callOptions ...callopt.Option) (r *addon.GetAddonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAddon(ctx, req)
}

func (p *kResourceServiceClient) CheckResourceExist(ctx context.Context, req *helper.CheckResourceExistRequest, callOptions ...callopt.Option) (r *helper.CheckResourceExistResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckResourceExist(ctx, req)
}

func (p *kResourceServiceClient) ListInstances(ctx context.Context, req *instance.ListInstancesRequest, callOptions ...callopt.Option) (r *instance.ListInstancesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListInstances(ctx, req)
}

func (p *kResourceServiceClient) ListFlavors(ctx context.Context, req *instance.ListFlavorsRequest, callOptions ...callopt.Option) (r *instance.ListFlavorsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFlavors(ctx, req)
}

func (p *kResourceServiceClient) GetInstanceConsole(ctx context.Context, req *instance.GetInstanceConsoleRequest, callOptions ...callopt.Option) (r *instance.GetInstanceConsoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInstanceConsole(ctx, req)
}

func (p *kResourceServiceClient) ListZones(ctx context.Context, req *instance.ListZonesRequest, callOptions ...callopt.Option) (r *instance.ListZonesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListZones(ctx, req)
}

func (p *kResourceServiceClient) ListVolumes(ctx context.Context, req *instance.ListVolumesRequest, callOptions ...callopt.Option) (r *instance.ListVolumesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListVolumes(ctx, req)
}

func (p *kResourceServiceClient) ListKeyPairs(ctx context.Context, req *instance.ListKeyPairsRequest, callOptions ...callopt.Option) (r *instance.ListKeyPairsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKeyPairs(ctx, req)
}

func (p *kResourceServiceClient) ListSubnets(ctx context.Context, req *vpc.ListSubnetsRequest, callOptions ...callopt.Option) (r *vpc.ListSubnetsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSubnets(ctx, req)
}

func (p *kResourceServiceClient) ListElasticIpPools(ctx context.Context, req *vpc.ListElasticIpPoolsRequest, callOptions ...callopt.Option) (r *vpc.ListElasticIpPoolsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListElasticIpPools(ctx, req)
}

func (p *kResourceServiceClient) ListVpcs(ctx context.Context, req *vpc.ListVpcsRequest, callOptions ...callopt.Option) (r *vpc.ListVpcsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListVpcs(ctx, req)
}

func (p *kResourceServiceClient) ListSecurityGroups(ctx context.Context, req *vpc.ListSecurityGroupsRequest, callOptions ...callopt.Option) (r *vpc.ListSecurityGroupsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSecurityGroups(ctx, req)
}

func (p *kResourceServiceClient) ListClbs(ctx context.Context, req *clb.ListClbsRequest, callOptions ...callopt.Option) (r *clb.ListClbsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListClbs(ctx, req)
}

func (p *kResourceServiceClient) ListClbListeners(ctx context.Context, req *clb.ListClbListenersRequest, callOptions ...callopt.Option) (r *clb.ListClbListenersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListClbListeners(ctx, req)
}

func (p *kResourceServiceClient) ListQuotas(ctx context.Context, req *quota.ListQuotasRequest, callOptions ...callopt.Option) (r *quota.ListQuotasResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListQuotas(ctx, req)
}

func (p *kResourceServiceClient) GetQuota(ctx context.Context, req *quota.GetQuotaRequest, callOptions ...callopt.Option) (r *quota.GetQuotaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetQuota(ctx, req)
}

func (p *kResourceServiceClient) CreateBareMachine(ctx context.Context, req *baremachine.CreateBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.CreateBareMachineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBareMachine(ctx, req)
}

func (p *kResourceServiceClient) UpdateBareMachine(ctx context.Context, req *baremachine.UpdateBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.UpdateBareMachineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateBareMachine(ctx, req)
}

func (p *kResourceServiceClient) DeleteBareMachine(ctx context.Context, req *baremachine.DeleteBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.DeleteBareMachineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteBareMachine(ctx, req)
}

func (p *kResourceServiceClient) GetBareMachine(ctx context.Context, req *baremachine.GetBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBareMachine(ctx, req)
}

func (p *kResourceServiceClient) ListBareMachine(ctx context.Context, req *baremachine.ListBareMachineRequest, callOptions ...callopt.Option) (r *baremachine.ListBareMachineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBareMachine(ctx, req)
}

func (p *kResourceServiceClient) GetBareMachineSshPublicKey(ctx context.Context, req *baremachine.GetBareMachineSshPublicKeyRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineSshPublicKeyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBareMachineSshPublicKey(ctx, req)
}

func (p *kResourceServiceClient) ListBareMachineExpectOs(ctx context.Context, req *baremachine.ListBareMachineExpectOsRequest, callOptions ...callopt.Option) (r *baremachine.ListBareMachineExpectOsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBareMachineExpectOs(ctx, req)
}

func (p *kResourceServiceClient) GetBareMachineImportExcelTemplate(ctx context.Context, req *baremachine.GetBareMachineImportExcelTemplateRequest, callOptions ...callopt.Option) (r *baremachine.GetBareMachineImportExcelTemplateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBareMachineImportExcelTemplate(ctx, req)
}

func (p *kResourceServiceClient) CheckCidrConflict(ctx context.Context, req *cluster.CheckCidrConflictRequest, callOptions ...callopt.Option) (r *cluster.CheckCidrConflictResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckCidrConflict(ctx, req)
}

func (p *kResourceServiceClient) RecommendCidr(ctx context.Context, req *cluster.RecommendCidrRequest, callOptions ...callopt.Option) (r *cluster.RecommendCidrResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecommendCidr(ctx, req)
}

func (p *kResourceServiceClient) AddVciSubnets(ctx context.Context, req *cluster.AddVciSubnetsRequest, callOptions ...callopt.Option) (r *cluster.AddVciSubnetsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddVciSubnets(ctx, req)
}

func (p *kResourceServiceClient) IsInShortTermWhiteList(ctx context.Context, req *trade.IsInShortTermWhiteListRequest, callOptions ...callopt.Option) (r *trade.IsInShortTermWhiteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IsInShortTermWhiteList(ctx, req)
}

func (p *kResourceServiceClient) AllowUserPublicTest(ctx context.Context, req *publicverify.PublicTestAllowedReq, callOptions ...callopt.Option) (r *publicverify.PublicTestAllowedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AllowUserPublicTest(ctx, req)
}

func (p *kResourceServiceClient) ListVciAvailabilityZones(ctx context.Context, req *vci.ListVciAvailabilityZonesRequest, callOptions ...callopt.Option) (r *vci.ListVciAvailabilityZonesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListVciAvailabilityZones(ctx, req)
}

func (p *kResourceServiceClient) ListNodeZones(ctx context.Context, req *cluster.ListNodeZonesRequest, callOptions ...callopt.Option) (r *cluster.ListNodeZonesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNodeZones(ctx, req)
}
