// Code generated by Kitex v0.1.0. DO NOT EDIT.
package appapiservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/volcengine/vkectl/pkg/model/app/kitex_gen/paastob/vke/appserver"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler appserver.AppAPIService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
